---
title: "Check_results"
author: "Carmen"
date: "March 23, 2018"
output: html_document
---

```{r}
library(tidyverse)
library(raster)
library(sp)
```


```{r}
setwd("~/drought_tree_carbon/drought_tree_carbon/results")
ag <- read.csv("Merced_aggregated.csv")
load("Results_Table_Merced.Rdata")
load("Results_Spatial_Merced.Rdata")
```

## Change columns to numeric
```{r}
head(ag)
ag[3:6] <- lapply(ag[,3:6],as.character)
ag[3:6] <- lapply(ag[,3:6],as.numeric)
head(ag)
```


```{r}
sumag <- ag %>% 
  summarise(liveBM = sum(na.omit(BM_live_2012_kg)), deadBM=sum(na.omit(D_BM_kg)), deadT = sum(na.omit(relNO_tot)), liveT = sum(na.omit(NO_TREES_PX)))
sumag            
```

```{r}
sumag$deadBM/sumag$liveBM
sumag$deadT/sumag$liveT
```

# Sum live biomass and live number of trees across the different data sets
```{r}
sum(spdf$BM_live_2012_kg)
sum(df$BM_live_2012_kg)
sum(na.omit(ag$BM_live_2012_kg))
```

## Troubleshoot
```{r}
sum(df$BM_live_2012_kg)/sum(na.omit(ag$BM_live_2012_kg))
```

Lots of live biomass in the aggregated data are missing. Why? Try the whole aggregation process and check live biomass along the way
```{r}
  # 1. Load Rdata with points in spdf
  layer <-"Colusa"
  load(paste("../results/Results_Spatial_", layer, ".Rdata", sep = ""))
  
  ## Ignore pixels with no starting biomass
  #summary(subset(spdf, is.na(spdf@data$BPH_abs))@data$D_BM_kg)
  spdf <- subset(spdf, !is.na(spdf@data$BPH_GE_25_CRM))
  spdf@data$BM_live_2012_kg <- spdf@data$BPH_GE_25_CRM*.09
##  
  sum(spdf$BM_live_2012_kg)
  # 2. Convert to a raster
  xyz <- spdf@data %>% 
    dplyr::select(x, y, BM_live_2012_kg, D_BM_kg, relNO_tot, NO_TREES_PX)
  sum(xyz$BM_live_2012_kg) == sum(spdf$BM_live_2012_kg)
  # Split in half if it's too large
  
  n <- nrow(xyz)/3
nr <- nrow(xyz)
xyz_split <- split(xyz, rep(1:ceiling(nr/n), each=n, length.out=nr))
  
    xyz1 <- xyz_split$`1`
    xyz2 <- xyz_split$`2`
    xyz3 <- xyz_split$`3`
    sum(na.omit(xyz1$BM_live_2012_kg)) + sum(na.omit(xyz2$BM_live_2012_kg)) + sum(na.omit(xyz3$BM_live_2012_kg)) == sum(spdf$BM_live_2012_kg)
    
    raster1 <- rasterFromXYZ(xyz1, crs= crs(spdf))
    raster2 <- rasterFromXYZ(xyz2, crs= crs(spdf))
    raster3 <- rasterFromXYZ(xyz3, crs= crs(spdf))
    # Check lengths
    length(raster1[[1]][!is.na(raster1[[1]])]) + length(raster2[[1]][!is.na(raster2[[1]])])+ length(raster3[[1]][!is.na(raster3[[1]])]) == nrow(spdf)
    
sum(na.omit(raster1[[1]]@data@values))+    sum(na.omit(raster2[[1]]@data@values))+    sum(na.omit(raster3[[1]]@data@values)) - sum(spdf$BM_live_2012_kg)
# close enough  
  
##  
    sum(na.omit(raster1[[1]]@data@values))-sum(xyz1$BM_live_2012_kg)
    sum(na.omit(raster2[[1]]@data@values)) - sum(xyz2$BM_live_2012_kg)
    sum(na.omit(raster3[[1]]@data@values))- sum(na.omit(xyz3$BM_live_2012_kg))
    
    remove(sum)
    # Use function aggregate to make it a coarser raster
    ag1 <- aggregate(raster1, fact = 33, fun = sum)
    ag2 <- aggregate(raster2, fact = 33, fun = sum)
    ag3 <- aggregate(raster3, fact = 33, fun = sum)
    
    sum(na.omit(ag1[[1]]@data@values))
    sum(xyz1$BM_live_2012_kg)
    sum(na.omit(ag2[[1]]@data@values))
    sum(xyz2$BM_live_2012_kg)
    sum(na.omit(ag3[[1]]@data@values))
    sum(na.omit(xyz3$BM_live_2012_kg))
    
    sum(na.omit(ag1[[1]]@data@values))+sum(na.omit(ag2[[1]]@data@values))+sum(na.omit(ag3[[1]]@data@values))
      
    sum(spdf$BM_live_2012_kg)
    
    layer_names <- c("BM_live_2012_kg", "D_BM_kg", "relNO_tot", "NO_TREES_PX")
    df_full <- data.frame()
   for(i in 1:4){
      
      bricklayer <- mosaic(ag1[[i]], ag2[[i]], fun = sum, tolerance = 0.05, na.omit = T)
      bricklayer <- mosaic(bricklayer, ag2[[i]], fun = sum, tolerance = 0.05, na.omit = T)
      
      sum(na.omit(bricklayer@data@values))
       
      sum(spdf$BM_live_2012_kg)
      sum(na.omit(ag1[[1]]@data@values))+sum(na.omit(ag2[[1]]@data@values))+sum(na.omit(ag3[[1]]@data@values))
       
       
      setwd("~/drought_tree_carbon/drought_tree_carbon/results/rasters_aggregated/")
      writeRaster(bricklayer, paste(layer, "_",layer_names[i],".tif",sep=""), driver = "ESRI Shapefile", overwrite = T)
      df <- as.data.frame(bricklayer, xy = T) %>% 
        setNames(c("x", "y",layer_names[i]))
      if(nrow(df_full) == 0){
        df_full <- df
        } else{
          df_full <- full_join(df_full, df)
        }
      assign(layer_names[i], bricklayer)
    }
    setwd("~/drought_tree_carbon/drought_tree_carbon/code/")
    write.csv(df_full, file = paste("../results/", layer, "_aggregated", ".csv", sep = ""), row.names = F)
  

```

# Not breaking up the raster
```{r}
sum(spdf$BM_live_2012_kg)
```

## make raster
```{r}
xyz <- spdf@data %>% 
    dplyr::select(x, y, BM_live_2012_kg, D_BM_kg, relNO_tot, NO_TREES_PX)
sum(xyz$BM_live_2012_kg)
raster <- rasterFromXYZ(xyz, crs= crs(spdf))
sum(na.omit(raster[[1]]@data@values))
```

## aggregate
```{r}
ag <- aggregate(raster, fact = 33, fun = sum)
sum(na.omit(ag[[1]]@data@values))
sum(xyz$BM_live_2012_kg) 

df <- as.data.frame(ag)

```

