---
title: "Get results for county-level live and dead biomass calculations"
author: "Carmen"
date: "July 27, 2018"
output: html_document
---

# Pull in functions
```{r}
setwd("~/drought_tree_carbon/drought_tree_carbon/code/")
library(rgeos)
library(rgdal)
source("transform_active.R")
source("biomass_calc_yearly.R")
source("map_yearly.R")
source("map.R")
source("aggregate_pixels.R")
```

# Look at counties
```{r}
setwd("~/drought_tree_carbon/drought_tree_carbon/code/")
load(file = "../data/CA_counties.Rdata")
to <- "~/drought_tree_carbon/drought_tree_carbon/data/active_unit/"
counties@data$NAME
plot(counties)
setwd("~/drought_tree_carbon/drought_tree_carbon/code/")
```

## Take out San Bernardino because it's too big to do all at once
```{r}
sb <- counties[counties$NAME == "San Bernardino",]
counties <- counties[counties$NAME != "San Bernardino",]
plot(counties)
```


# Loop the functions over all counties except San Bernardino
```{r}
for(i in 32:length(counties)){
  print(i)
  # Remove county from folder
  active_county <- list.dirs("~/drought_tree_carbon/drought_tree_carbon/data/active_unit/", recursive = F)
  unlink(active_county, recursive = T)
  
  # Save new county to folder named that county
  county <- counties[i,]
  setwd("~/drought_tree_carbon/drought_tree_carbon/data/active_unit/")
  lay <- as.character(county@data$NAME)
  dir.create(lay)
  print(lay)
  writeOGR(obj = county, dsn = lay, layer = lay, driver = "ESRI Shapefile")
  setwd("~/drought_tree_carbon/drought_tree_carbon/code/")
  transform()
  
  biomass_calc_yearly()
  map_yearly()
  map()
  aggregate_pixels()
}
```


# Do San Bernardino separately because it's too big for my RAM to do on its own


## Split the San Bernardino polygon into two chunks
```{r}
plot(sb)
esb <- extent(sb)
halfway <- extent(sb)[4] - (extent(sb)[4] - extent(sb)[3])/2
e1 <- extent(esb[1], esb[2], halfway, esb[4])
e2 <- extent(esb[1], esb[2], esb[3], halfway)
sb1 <- crop(sb, e1)
sb2 <- crop(sb, e2)
plot(sb1, add = T, col = "pink")
plot(sb2, add = T, col = "light blue")
```

## Save the two chunks 
```{r}
save(sb1, file = "~/drought_tree_carbon/drought_tree_carbon/data/SanBernardino1.Rdata")
save(sb2, file = "~/drought_tree_carbon/drought_tree_carbon/data/SanBernardino2.Rdata")
```

## Repeat the above code for sb1 and sb2
```{r}
counties <- c(sb1, sb2)
for(i in 1:length(counties)){
  print(i)
  
  # Remove county from folder
  active_county <- list.dirs("~/drought_tree_carbon/drought_tree_carbon/data/active_unit/", recursive = F)
  unlink(active_county, recursive = T)
  
  # Save new county to folder named that county
  county <- counties[i][[1]]
  setwd("~/drought_tree_carbon/drought_tree_carbon/data/active_unit/")
  lay <- as.character(paste(county@data$NAME, i))
  dir.create(lay)
  print(lay)
  writeOGR(obj = county, dsn = lay, layer = lay, driver = "ESRI Shapefile")
  setwd("~/drought_tree_carbon/drought_tree_carbon/code/")
  transform()
  
  biomass_calc_yearly() # Calculating live biomass takes the most time by far of any step in counties with sparse mortality, so try to only do that once
  map_yearly()
  map()
  aggregate_pixels()
}
```
