---
title: "Save spatial results as one file"
author: "Carmen"
date: "July 17, 2018"
output: html_document
---

```{r}
require(tidyverse)
require(rgeos)
require(rgdal)
```

# Pull up one county and check it
```{r}
setwd("~/drought_tree_carbon/drought_tree_carbon/results/Counties/Results_spatial/")
load("Results_Spatial_Orange.Rdata")
names(spdf)
spdf@data <- spdf@data %>% 
  dplyr::select(pixel_key, x, y, D_BM_kg, BM_live_2012_kg, Percent_Mortality_Biomass)
```

# Rename to shorter names
```{r}
spdf@data <- spdf@data %>% 
  rename(PercDeadBM = Percent_Mortality_Biomass) %>% 
  rename(DeadBMkg = D_BM_kg) %>% 
  rename(LiveBMkg = BM_live_2012_kg)
```


# Replace NA dead biomass with 0
```{r}
spdf@data <- spdf@data %>% 
  mutate(PercDeadBM = ifelse(is.na(PercDeadBM), 0, PercDeadBM)) %>% 
  mutate(DeadBMkg = ifelse(is.na(DeadBMkg ), 0, DeadBMkg)) 
```

## Check
```{r}
ggplot(spdf@data)+
  geom_tile(aes(x = x, y = y, col = PercDeadBM))+
  scale_color_gradient(low="light gray", high="red")

ggplot(spdf@data)+
  geom_tile(aes(x = x, y = y, col = DeadBMkg))+
  scale_color_gradient(low="light gray", high="red")

ggplot(spdf@data)+
  geom_tile(aes(x = x, y = y, col = LiveBMkg))+
  scale_color_gradient(low="light gray", high="red")
```

## Save
```{r}
setwd("~/drought_tree_carbon/drought_tree_carbon/results/IGIS")
save(spdf, file = "Orange25.Rdata")
```


# Loop it across all counties

## Load and prep county perimeters
```{r}
setwd("~/drought_tree_carbon/drought_tree_carbon/")
load(file = "data/CA_counties.Rdata")
sort(counties@data$NAME)
counties <- counties[counties$NAME != "San Bernardino",]
plot(counties)
```

## Loop it across all counties except San Bernardino (which is too big to do all at once)
```{r}
plot(counties)
for(i in 1:length(counties)){
  print(i)
  setwd("~/drought_tree_carbon/drought_tree_carbon/results/Counties/Results_spatial/")
  result_file <- paste("Results_Spatial_", lay, ".Rdata", sep = "")
  load(result_file)
  spdf@data <- spdf@data %>% 
    dplyr::select(pixel_key, x, y, D_BM_kg, BM_live_2012_kg, Percent_Mortality_Biomass)
  spdf@data <- spdf@data %>% 
    rename(PercDeadBM = Percent_Mortality_Biomass) %>% 
    rename(DeadBMkg = D_BM_kg) %>% 
    rename(LiveBMkg = BM_live_2012_kg)
  spdf@data <- spdf@data %>% 
    mutate(PercDeadBM = ifelse(is.na(PercDeadBM), 0, PercDeadBM)) %>% 
    mutate(DeadBMkg = ifelse(is.na(DeadBMkg ), 0, DeadBMkg)) 
  setwd("~/drought_tree_carbon/drought_tree_carbon/results/IGIS")
  final_file <- paste(lay, "25.Rdata", sep = "") 
  save(spdf, file = final_file)
  plot(spdf, add = T, pch = ".")
}
```

# Do the same for just San Bernardino northern and southern halves


```{r}
sb <- c("San Bernardino 1", "San Bernardino 2")
for(i in c(1,2)){
  lay <- sb[i]
  result_file <- paste("~/drought_tree_carbon/drought_tree_carbon/results/Counties/Results_spatial/Results_Spatial_", lay, ".Rdata", sep = "")
  load(result_file)
  spdf@data <- spdf@data %>% 
    dplyr::select(pixel_key, x, y, D_BM_kg, BM_live_2012_kg, Percent_Mortality_Biomass)
  spdf@data <- spdf@data %>% 
    rename(PercDeadBM = Percent_Mortality_Biomass) %>% 
    rename(DeadBMkg = D_BM_kg) %>% 
    rename(LiveBMkg = BM_live_2012_kg)
  spdf@data <- spdf@data %>% 
    mutate(PercDeadBM = ifelse(is.na(PercDeadBM), 0, PercDeadBM)) %>% 
    mutate(DeadBMkg = ifelse(is.na(DeadBMkg ), 0, DeadBMkg)) 
  setwd("~/drought_tree_carbon/drought_tree_carbon/results/IGIS")
  final_file <- paste(lay, " 25.Rdata", sep = "") 
  save(spdf, file = final_file)
  plot(spdf, add = T, pch = ".")
}
```

