---
title: "Drought Mortality Biomass Calculations README"
author: "Carmen"
date: "October 5, 2017"
output: 
  github_document
---

Calculate the biomass of trees that have died in recent drought/insect mortality in all California counties.

This is a spinoff of github.com/WoodResourcesGroup/EPIC_AllPowerLabs/tree/master/Biomass

# Script sequence for each of DBH_3_cm and DBH_25_cm

1.  `GET_RESULTS_COUNTIES_*.Rmd` executes the following in this order for each county or, in the case of San Bernardino, half county:
    * empties `data/active_unit` folder
    * saves county perimeter from `data/CA_counties` in the folder `data/active_unit`
    * transform()
    * biomass_calc_yearly()
    * map_yearly()
    * map()
    * aggregate_pixels()


# Output Variables


| Code | Description | Source(s) of data |
| :------------------------ | :------------------------- | :----------------------------- |
| `pixel_key` | Unique pixel ID | Analysis |
| `x` | X coordinate of pixel center | `LEMMA` |
| `y` | Y coordinate of pixel center | `LEMMA` |
| `LiveBMkg` | Biomass of live trees >25 cm in the pixel (kg) | `BPH_GE_25_CRM` multiplied by .09 |
| `DeadBMkg` | Estimated biomass of dead trees in the pixel in kg | `LEMMA` & `drought` |
| `PercDeadBM` | Biomass of all trees that died divided by biomass of live trees in 2012 | `DeadBMkg/LiveBMkg`  |


